/*
  Tema 4: Pipelines CI/CD
	Práctica 2
	. Jenkinsfile dummy (PUNTO DE PARTIDA) #Done
	. Añadir stage 'Info' #Done
	. Añadir stage 'CI - Build tools image' & 'CI - Lint' #Doing

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/

pipeline {
  agent any

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
        echo "Branch: ${env.BRANCH_NAME}"
      }
    }

    stage('CI - Build tools image') {
      steps {
        script {
          env.CI_IMAGE_NAME = "java-ci-tools:${env.BUILD_NUMBER}"
          docker.build(env.CI_IMAGE_NAME, "-f devops/ci.Dockerfile .")
        }
      }
    }

    stage('CI - Lint') {
      steps {
        script {
          docker.image(env.CI_IMAGE_NAME).inside {
            sh 'make lint'
          }
        }
      }
    }

    stage('CI - Test') {
      steps {
        script {
          docker.image(env.CI_IMAGE_NAME).inside {
            sh 'make test'
          }
        }
      }
    }
  }
}
