def runInDocker(String image, Closure body) {
  docker.image(image).inside {
    body()
  }
}
pipeline {
  agent any
  parameters {
    booleanParam(name: 'RUN_CD', defaultValue: true, description: 'Ejecutar CD')
  }
  environment {
    IMAGE_NAME = "java-hello-world:${env.BUILD_NUMBER}"
    APP_URL = "http://localhost:8084"
  }
  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
        echo "Branch: ${env.BRANCH_NAME}"
        echo "Comprobando ejecución después de push"
      }
    }
    stage('CI - Build tools image') {
      steps {
        script {
          env.CI_IMAGE_NAME = "java-ci-tools:${env.BUILD_NUMBER}"
          docker.build(env.CI_IMAGE_NAME, "-f devops/ci.Dockerfile .")
        }
      }
    }
    stage('CI - Lint') {
      steps {
        script {
          runInDocker(env.CI_IMAGE_NAME) {
            sh 'make lint'
          }
        }
      }
    }
    stage('CI - Test') {
      steps {
        script {
          runInDocker(env.CI_IMAGE_NAME) {
            sh 'make test'
          }
        }
      }
    }
    stage('CI - SonarQube Analysis') {
      steps {
       withSonarQubeEnv('SonarQube') {
         //sh 'mvn sonar:sonar -Dsonar.projectKey=DevOps -Dsonar.projectName=\'Github\' -Dsonar.host.url=http://192.168.50.201:9000'
         sh '''
           sonar-scanner \
             -Dsonar.projectKey=DevOps \
             -Dsonar.projectName="Github" \
             -Dsonar.sources=. \
             -Dsonar.java.binaries=target \
             -Dsonar.host.url=http://sonarqube:9000 \
             -Dsonar.ws.timeout=120  
         '''       
       }
     }
    }
    stage('CI - Build image') {
      steps {
        script {
          docker.build(env.IMAGE_NAME, "--build-arg VERSION=0.0.1-SNAPSHOT -f devops/Dockerfile .")
        }
      }
    }
    stage('CD') {
      when {
        allOf {
          anyOf {
            branch 'develop'
            branch 'master'
          }
          expression { return params.RUN_CD }
        }
      }
      steps {
        script {
          env.DEPLOY_ENV = env.BRANCH_NAME == 'master' ? 'PRO' : 'DEV'
          echo "Entorno: ${env.DEPLOY_ENV}"
          echo "Image: ${env.IMAGE_NAME}"
          echo "App URL: ${env.APP_URL}"
        }
      }
    }
  }
  post {
    always {
      script {
        if (env.BRANCH_NAME == 'develop' || env.BRANCH_NAME == 'master') {
          echo "Limpiando recursos..."
          sh "docker compose down --volumes || true"
        }
      }
    }
    success {
      echo "Pipeline finalizado correctamente ✅"
    }
    failure {
      echo "Pipeline ha fallado ❌"
    }
  }
}
