/*
  Tema 4: Pipelines CI/CD
	Práctica 2
	. Jenkinsfile dummy (PUNTO DE PARTIDA) #Done
	. Añadir stage 'Info' #Done
	. Añadir stage 'CI - Build tools image' & 'CI - Lint' #Doing

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/

def runInDocker(String image, Closure body) {
  docker.image(image).inside {
    body()
  }
}

pipeline {
  agent any
  parameters {
    booleanParam(name: 'RUN_CD', defaultValue: true, description: 'Ejecutar CD')
  }

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
        echo "Branch: ${env.BRANCH_NAME}"
      }
    }

    stage('CI - Build tools image') {
      steps {
        script {
          env.CI_IMAGE_NAME = "java-ci-tools:${env.BUILD_NUMBER}"
          docker.build(env.CI_IMAGE_NAME, "-f devops/ci.Dockerfile .")
        }
      }
    }

    stage('CI - Lint') {
      steps {
        script {
          runInDocker(env.CI_IMAGE_NAME) {
            sh 'make lint'
          }
        }
      }
    }

    stage('CI - Test') {
      steps {
        script {
          runInDocker(env.CI_IMAGE_NAME) {
            sh 'make test'
          }
        }
      }
    }

    stage('CI - Build image') {
      steps {
        script {
          env.IMAGE_NAME = "java-hello-world:${env.BUILD_NUMBER}"
          docker.build(env.IMAGE_NAME, "--build-arg VERSION=0.0.1-SNAPSHOT -f devops/Dockerfile .")
        }
      }
    }

    stages {
    // ... stages anteriores igual ...
    stage('CD') {
      when {
        allOf {
          anyOf {
            branch 'develop'
            branch 'master'
          }
          expression { return params.RUN_CD }
        }
      }
      steps {
        script {
          env.DEPLOY_ENV = env.BRANCH_NAME == 'master' ? 'PRO' : 'DEV'
          echo "Rama ${env.BRANCH_NAME} → entorno: ${env.DEPLOY_ENV}"
        }
      }
    }
  }
}
