version: "3.7"
networks:
  java-project-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.234.0/24
volumes:
  prometheus-data:
  grafana-data:
services:
  app:
    build:
      context: .
      dockerfile: devops/Dockerfile
    container_name: java_app
    ports:
      - 8084:8080
    networks:
      java-project-net:
        aliases:
          - app

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./devops/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      java-project-net:
        aliases:
          - prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      java-project-net:
        aliases:
          - grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
