# configuring port number on which application should run
#server.port=8081
# Actuator: exponer endpoints de monitorización
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=spring-boot-2-hello-world
management.metrics.distribution.percentiles-histogram.http.server.requests=true
