# Práctica 3 - GitHub Actions (dummy)
name: CI (dummy)
on:
  workflow_dispatch:
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar contexto
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref:  $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
